### ISSUE TITLE
AppStore reviewer can't buy In-App purchase

### ISSUE THREAD

**Issue by jeromebarnoin** [PeterStaev/nativescript-purchase#100]
Hello,
I'm stuck in the process for publishing.
My products included in the App, can't be verify by the App Store reviewer.
They are non-renewal subscriptions and I don't check the validate the receipt of the transaction for now.
Everything work fine in TestFlight.
But every time the reviewer try to buy the server return a transaction with status : failed.

I would like to know if you have trouble too with the review of products.
And if you have solutions for this kind of situation.

nativescript version : 5.2.0 
nativescript-purchase : 2.0.13

The message of the reviewer : 

Guideline 2.1 - Performance - App Completeness

We found that your in-app purchase products exhibited one or more bugs when reviewed on iPad running iOS 13.4.1 on Wi-Fi.

Specifically, an error message is still displayed when we attempt to complete a purchase.

![attachment](https://user-images.githubusercontent.com/1755424/83696669-52a3d900-a5fd-11ea-85fa-add5a182b7a3.png)

**Comment by PeterStaev** [comment]
Hey @jeromebarnoin , 

Sadly I dont have any experience in publishing apps with purchases on the store, so not sure how accurate my comment below is. 

From what I can see you are using subscriptions? So I suspect this error comes from your backend validation process. Not sure how you have implemented this but according to Apple's guidelines - when your app is in testflight/review the validation must happen with the sandbox URL, while when your app is on the store, it should use the production URL. Below is the note on how to correctly implement validation so that it works both when testing, review and when you app is in production:
>Important
Verify your receipt first with the production URL; then verify with the sandbox URL if you receive a 21007 status code. This approach ensures you do not have to switch between URLs while your application is tested, reviewed by App Review, or live in the App Store.

**Comment by jeromebarnoin** [comment]
Thank you to reply so quickly.

I don't think my issue is related to the verification, because no transactionReceipt were generate.
So I have nothing to verify.
I sended them a new build with an debugging improvement  
Now It will record in a log file on my server

- the products list loaded from the apple server,
- On every transactionUpdatedEvent it will log the transaction object

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
