### ISSUE TITLE
Feature request: Angular support 

### ISSUE THREAD

**Issue by NickIliev** [PeterStaev/nativescript-purchase#12]
Currently using the plugin in Angular will throw with
```
No provider for Product!
```

in a scenario where we are using Product as argument in our component constructor
```
export class AppComponent { 

    constructor(private product: Product) { }
}
```

Are there plans to provide Angular support for this plugin? (Requested by community members of NativeScript)

**Comment by PeterStaev** [comment]
Hey @NickIliev , 
The error is because you cannot initialize a `Product` directly with dependency injection. Like written in the readme the `Product` cannot be created from user code and is required to be the one that is returned from the `getProducts` method. So if the user wants to use DI then they must implement their own provider for the product and specify to pull it from the list of already loaded products.
