### ISSUE TITLE
Purchasing a non-renewable-subscription IAP again.

### ISSUE THREAD

**Issue by erjdriver** [PeterStaev/nativescript-purchase#28]
I know subscriptions are not supported...

Under iOS, I've got non-renewable subscriptions and by and large they seem to work.

But when I go to buy the same product the second time - I get an Apple dialog - that says already purchased and restoring for free.

But in the plug-in callback, the transactionState is Purchased not Restored. Also all the dates etc are from a previous transaction.

That's fine - but I was wondering:

1. why the transactionState was Purchased when the Apple dialog said Restored for free.

2. how would one purchase second time.

Even though it's a non-renewable subscription - I did add the consume() code - even though the docs said it was required only for Android.

**Comment by PeterStaev** [comment]
Hey @erjdriver , since the plugin utilizes the native iOS objects, your best bet will be to check why it is working like that on the native platform. 

About 1 - The plugin directly maps what iOS returns to the plugin's `TransactionState` enum [here](https://github.com/PeterStaev/nativescript-purchase/blob/master/transaction/transaction.ios.ts#L25). So this means that Apple sends the transaction as purchased. But why it is doing that I dont have a clue. 

About 2 - I'm not sure how exactly non-renewing subscriptions are working as I have not looked into details the API. But from what I read those are time based. So somehow you should handle when it is time to renew. You can take a look at the following article: https://www.raywenderlich.com/147629/in-app-purchases-non-renewing-subscriptions-tutorial

**Comment by erjdriver** [comment]
Thank you.

I will look into this and try to get back.

Since I'm managing the subscription myself - looks like non-renew. subs will not work for me....I'm pretty sure when I added the products in iTunes there was nothing about duration - so not sure how Apple can manage it either.

I think ideally consumable IAP would work for me - but not sure if Apple will allow that.

Thanks for your response - I'll do some research and try to get back.

Quick question - is all the code for the ios in ts/js - i.e. no native code?

And a dumb question - I noticed that the plugin is written in TS - but the plugin code that i've installed is all js. If I want to do some editing how can that be done - i.e. small edits in the plugin while it's within my app's node_modules folder.
