### ISSUE TITLE
get products

### ISSUE THREAD

**Issue by mendokar** [PeterStaev/nativescript-purchase#29]
hello peter, I communicate with you because I'm using your plugin because I need to implement payments in my App but I'm working with Angular and the getProducts method does not work, I send you my code I hope you can help me.

I have followed the steps of your tutorial but the plugin methods do not work, I am using the latest version of NS.

https://www.tangrainc.com/blog/2017/02/implementing-app-purchases-nativescript-application-part-1/

thanks

**Comment by PeterStaev** [comment]
Hey @mendokar , 

Where do you call the `init` method in your Angular app? Also make sure that you read the other parts of the article as it is a little bit tricky to make `getProducts()` to work especially for android.

**Comment by mendokar** [comment]
I'm creating an example, could you tell me if I'm doing something please, I leave the repository, thank you.

https://github.com/mendokar/purchases_NS

**Comment by PeterStaev** [comment]
From what I see you are not calling `init()` in your `main.aot.ts` file. This means that if you are using AoT then the plugin will not be working.

**Comment by mendokar** [comment]
Hello Piter I have not yet been able to make my application work with payments, you could contact me directly to my email or Skype to work, I could pay for your collaboration, it is very important for me, thanks.

My email is Oscar.mendozaruiz@hotmail.com

**Comment by PeterStaev** [comment]
Sorry for the late response, but had lots of things here. Sadly I wont have the time to do the collaboration you want due to other projects that I'm working on that are coming to a deadline soon. I suggest you go step by step with the guides I have posted. Another possibility is you ask for help on the NativeScript forums. There is a chance there would be a user that experienced the same hurdles and could guide you on what are you missing.
