### ISSUE TITLE
Feature: promotions

### ISSUE THREAD

**Issue by yavulan** [PeterStaev/nativescript-purchase#51]
Is implementing a [promotion](https://developer.android.com/google/play/billing/billing_onetime#Implement-promo) planned?

Thank you.

**Comment by PeterStaev** [comment]
Hey @yavulan , for the time being I have no ETA when/if that feature will be implemented. I'm happily accepting PRs if you (or someone else) want to add this to the code 😉

**Comment by PeterStaev** [comment]
Hey @yavulan , I've just reviewed the Google docs about promotions and seems those should be supported out of the box since the plugin uses the native API calls and doesn't have any custom UI related for purchases. 
So looking at the steps here: https://developer.android.com/google/play/billing/billing_promo I do not see anything special that needs to be used to call the native APIs in order to work with promo codes. 

Have you tried using promo codes? If so what problems did you get that you think require changes to the plugin code?

**Comment by yavulan** [comment]
Thank you for the response.

It is hard to recall details of the problem I run into in 2018.
Also, I shifted a bit from using NativeScript since then, so I can't provide you with useful information regarding this issue.

I suggest to hear out @apsaros, who upvoted the issue.

Merry Christmas & Весела Коледа!

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
